export const GUIDE_SAMPLES = {
  'pungjeong-kitsch': {
    id: 'pungjeong-kitsch',
    label: '龍 Dragon 풍정 키치',
    presetId: 'kitsch-sticker',
    studioTab: 'allinone',
    stickerOn: true,
    stickerTheme: 'fnb',
    previewBg: 'checker',
    layers: {
      main: {
        text: '龍 Dragon 풍정',
        fontId: 'jalnan',
        presetId: 'kitsch-sticker',
        fontSize: 70,
        fontWeight: 400,
        color: '#F6E7C1',
        strokeWidth: 0,
        strokeWidth2: 0,
        curveAmount: 0,
        ox: 0,
        oy: 0,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.2,
        align: 'center',
      },
      sub: {
        text: 'AI Text Styler',
        fontId: 'great-vibes',
        presetId: '',
        fontSize: 40,
        color: '#e0f2fe',
        strokeWidth: 0,
        strokeWidth2: 0,
        curveAmount: 0,
        ox: 0,
        oy: 0.24,
        rotation: 0,
      },
    },
  },
  'gold-dragon': {
    id: 'gold-dragon',
    label: '황금 용 캘리그라피',
    presetId: 'traditional-calligraphy',
    studioTab: 'calligraphy',
    layers: {
      main: {
        text: '황금용',
        fontId: 'nanum-brush',
        presetId: 'traditional-calligraphy',
        fontSize: 128,
        fontWeight: 400,
        color: '#fbbf24',
        strokeColor: '#7c2d12',
        strokeWidth: 3,
        strokeColor2: '#f59e0b',
        strokeWidth2: 6,
        curveAmount: 28,
        ox: 0,
        oy: 0,
        rotation: -4,
        letterSpacing: 6,
        lineHeight: 1.15,
        align: 'center',
      },
      sub: {
        text: 'Golden Dragon',
        fontId: 'great-vibes',
        presetId: '',
        fontSize: 38,
        color: '#fde68a',
        strokeWidth: 0,
        strokeWidth2: 0,
        curveAmount: 0,
        ox: 0,
        oy: 0.28,
        rotation: 0,
      },
    },
  },
  'neon-cyber': {
    id: 'neon-cyber',
    label: '네온 사이버펑크',
    presetId: 'cyber-neon',
    studioTab: 'allinone',
    gifMotion: 'pulse',
    layers: {
      main: {
        text: 'CYBER',
        fontId: 'black-han',
        presetId: 'cyber-neon',
        fontSize: 120,
        fontWeight: 700,
        color: '#22d3ee',
        strokeColor: '#a78bfa',
        strokeWidth: 2,
        strokeColor2: '#0f172a',
        strokeWidth2: 7,
        curveAmount: 0,
        ox: 0,
        oy: 0,
        rotation: 0,
        letterSpacing: 2,
      },
      sub: {
        text: '2077 TITLE',
        fontId: 'rubik-glitch',
        presetId: '',
        fontSize: 30,
        color: '#f472b6',
        strokeWidth: 0,
        strokeWidth2: 0,
        curveAmount: 0,
        oy: 0.26,
      },
    },
  },
  'kakao-sticker': {
    id: 'kakao-sticker',
    label: '카카오 스티커 타이틀',
    presetId: 'kitsch-sticker',
    studioTab: 'allinone',
    layers: {
      main: {
        text: '카카오 스티커',
        fontId: 'jalnan',
        presetId: 'kitsch-sticker',
        fontSize: 92,
        color: '#3c1e1e',
        strokeColor: '#fff7ed',
        strokeWidth: 4,
        strokeColor2: '#ea580c',
        strokeWidth2: 8,
        curveAmount: -16,
        ox: 0,
        oy: 0,
        rotation: 0,
        letterSpacing: 1,
      },
      sub: {
        text: '360×360 PNG',
        fontId: 'cookierun',
        presetId: '',
        fontSize: 28,
        color: '#9a3412',
        strokeWidth: 0,
        strokeWidth2: 0,
        curveAmount: 0,
        oy: 0.3,
      },
    },
  },
}

export function applyGuideSample(studio, sample) {
  if (!studio || !sample) return studio
  return {
    ...studio,
    presetId: sample.presetId ?? studio.presetId,
    studioTab: sample.studioTab ?? studio.studioTab,
    gifMotion: sample.gifMotion ?? studio.gifMotion,
    stickerOn: sample.stickerOn ?? studio.stickerOn,
    stickerTheme: sample.stickerTheme ?? studio.stickerTheme,
    previewBg: sample.previewBg ?? studio.previewBg,
    layers: (studio.layers || []).map((layer) => {
      const patch = sample.layers?.[layer.role]
      if (!patch) return layer
      return { ...layer, ...patch }
    }),
  }
}
